### ISSUE TITLE
Non-Storage Devices on PCIe Gen 3.0 Slot

### ISSUE THREAD

**Issue by champlainmorin** [edk2-porting/edk2-rk35xx#9]
I attached a graphics device to the PCIe 3.0 slot using an M.2 adapter to full size slot with an external PSU for power, and I noticed extreme slowdowns with EFI, to the point where loading an image was impossible. However, the PCI device was recognized in the EFI shell. Any ideas on what's causing this?

**Comment by mariobalanica** [comment]
Can you provide a serial log from latest debug build?
